apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: task4
subjects:
- kind: User
  name: alex # Имя пользователя из CSR
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role # Имя роли, которую создали выше
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: analyst-binding
subjects:
- kind: User
  name: grisha
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: analyst
  apiGroup: rbac.authorization.k8s.io
